name: Extension Issue Report
description: Extension cannot be installed or not working as expected
title: "[Extension]: "
labels: ["extension"]

body:
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Tell us what happened in a very clear and simple way
      value: Please fill this form with as much information as possible
  - type: textarea
    id: platform
    attributes:
      label: Version Platform Description
      description: Describe your platform (program version, OS, browser)
      value: 
  - type: markdown
    attributes:
      value: |
        Any issues without version information will be closed  
        Provide any relevant platorm information:  
        - Application version, OS details, GPU information, browser used  
        Easiest is to include top part of console log  
        Example:  
        ```log
        Starting SD.Next
        Python 3.10.6 on Linux
        Version: abd7d160 Sat Jun 10 07:37:42 2023 -0400
        nVidia CUDA toolkit detected
        Torch 2.1.0.dev20230519+cu121
        Torch backend: nVidia CUDA 12.1 cuDNN 8801
        Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28
        Enabled extensions-builtin: [...]
        Enabled extensions: [...]
        ```
  - type: input
    id: url
    attributes:
      label: URL link of the extension
      description: URL link of the extension
      value: 
    validations:
      required: true
  - type: input
    id: issue
    attributes:
      label: URL link of the issue reported in the extension repository
      description: Any extension related issue must also be reported to extension repository as well
      value: 
  - type: markdown
    attributes:
      value: |
        Any issues without version information and actual link to extension will be closed  
  - type: markdown
    attributes:
      value: |
        If issue is extension installation or startup related, please check `sdnext.log` before reporting  
        And when posting console logs, please use code blocks ( \`\`\` ) to format them insead of uploading screenshots  
  - type: markdown
    attributes:
      value: |
        If unsure if this is a right place to ask your question, perhaps post on [Discussions](https://github.com/vladmandic/automatic/discussions)
        Or reach-out to us on [Discord](https://discord.gg/WqMzTUDC)
  - type: checkboxes
    attributes:
      label: Acknowledgements
      description: 
      options:
        - label: I have read the above and searched for existing issues
          required: true
