name: lint-on-push

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3
      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: pip
          cache-dependency-path: requirements.txt
      - name: run-ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          ruff .
      # - name: run-pylint
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install pylint
      #    pylint $(git ls-files '*.py')
      - name: test-startup
        run: |
          export COMMANDLINE_ARGS="--debug --test"
          python launch.py
